version: '3'
services:
  your-service-name:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8082:80
    volumes:
      - .:/app
    networks:
      - gl
networks:
  gl:
    driver: bridge